#!/usr/bin/env bash

# test the presence of the interactive flag
interactive=false
for var in "$@" 
do
    if [ $var == "-i" ]; then
	echo 'interactive mode'
	interactive=true
    fi
done

if [ "$interactive" = true ]; then
    args=`echo $@ | sed -e 's#-i##g'`
    ln -sf $HEPPY/scripts/heppy_interactive.py tmp_heppy.py
    ipython -i tmp_heppy.py -- $args
else
    ln -sf $HEPPY/scripts/heppy_loop.py tmp_heppy.py
    ipython -- tmp_heppy.py "$@"
fi 
rm tmp_heppy.py
